name: 自動打包並上傳

on:
  push:
    branches:
      - main


permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 克隆仓库
        uses: actions/checkout@v2

      - name: 安裝 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 安裝必要的 npm 資產
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm install
        
      - name: 壓縮兩個資料夾
        run: |
          mkdir output
          zip -r output/TNTCoinImprove.mcaddon [BP]iiTNTC [RP]iiTNTC
          zip -r output/TNTCoinImproveBP.mcpack [BP]iiTNTC
          zip -r output/TNTCoinImproveRP.mcpack [RP]iiTNTC

      - name: 檢查並創建 RELEASE_LOG.md 文件
        run: |
          if [ ! -f RELEASE_LOG.md ]; then
            echo "## 新Release Log" > RELEASE_LOG.md
          fi
      - name: 生成 Release 日誌
        id: log
        run: |
          # 獲取最近的提交訊息
          RECENT_COMMITS=$(git log -5 --pretty=format:"%h - %s")

          # 更新 RELEASE_LOG.md 文件
          echo "$RECENT_COMMITS" >> RELEASE_LOG.md

          # 打印提交訊息到終端
          echo "Recent commits: $RECENT_COMMITS"



      - name: 檢查並更新舊的 release 草稿
        uses: actions/github-script@v6
        with:
           script: |
             const { owner, repo } = context.repo;
             const releases = await github.repos.listReleases({ owner, repo });
             const draftRelease = releases.data.find(release => release.draft);
             if (draftRelease) {
               const release_id = draftRelease.id;
               github.repos.updateRelease({
                 owner,
                 repo,
                 release_id,
                 body: fs.readFileSync('RELEASE_LOG.md', 'utf8')
               });
               core.setOutput('release_id', release_id);
             } else {
                const newRelease = await github.repos.createRelease({
                owner,
                repo,
                tag_name: 'v1.0.0',
                name: 'v1.0.0',
                body: fs.readFileSync('RELEASE_LOG.md', 'utf8'),
                draft: true
              });
              core.setOutput('release_id', newRelease.data.id);
             }

            
      - name: 上傳到 GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/TNTCoinImprove.mcaddon
            output/TNTCoinImproveBP.mcpack
            output/TNTCoinImproveRP.mcpack
          draft: true
          body_path: RELEASE_LOG.md
