name: 自動打包並上傳

on:
  push:
    branches:
      - main


permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 克隆仓库
        uses: actions/checkout@v2

      - name: 安裝 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 安裝必要的 npm 資產
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm install
        
      - name: 壓縮兩個資料夾
        run: |
          mkdir output
          zip -r output/TNTCoinImprove.mcaddon [BP]iiTNTC [RP]iiTNTC
          zip -r output/TNTCoinImproveBP.mcpack [BP]iiTNTC
          zip -r output/TNTCoinImproveRP.mcpack [RP]iiTNTC


      - name: 生成 Release 日誌
        id: log
        run: |
          RECENT_COMMITS=$(git log -5 --pretty=format:"%h - %s")
          echo "## 新 Release" >> RELEASE_LOG.md
          echo "$RECENT_COMMITS" >> RELEASE_LOG.md
          echo "recent_commits=$RECENT_COMMITS" >> $GITHUB_OUTPUT
          
      - name: 上傳到 GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/TNTCoinImprove.mcaddon
            output/TNTCoinImproveBP.mcpack
            output/TNTCoinImproveRP.mcpack
          draft: true
          body: ${{ steps.log.outputs.recent_commits }}
